PWX-36080 - Added files for policy to use apiversion v1
portworx/sched-ops pull request #355
Opened 2024-02-13 09:14 UTC by svijaykumar-px

**What this PR does / why we need it**: Currently the poddisruptionbudget uses api version policy/v1beta1. But this was removed from kubernetes version 1.25 ( [refer to this link](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125) . It was decided to keep the existing API as well.

**Which issue(s) this PR fixes** (optional)
Closes # PWX-36080

**Special notes for your reviewer**: This change is necessary to write operator integration tests for poddisruptionbudget as the old api version does not work.

2024-02-13 18:29 UTC, piyush-nimbalkar requested changes

2024-02-13 18:29 UTC, piyush-nimbalkar commented on k8s/policyV1/poddisruptionbudgetV1.go
- Let's keep all the policy APIs in one folder under `k8s/policy`.
- Let's rename the old Ops and file as PodDisruptionBudgetV1Beta1Ops and poddisruptionbudget_v1beta1.go respectively. Also, let's rename the methods in it to have a V1Beta1 suffix just like the apiextensions package.
- Add a new file called poddisruptionbudget.go and have the v1 Ops and APIs in it without any suffix.
- People who vendor the latest sched-ops will rename their old methods to have the V1Beta1 suffix or change their API version to the newer one.

2024-02-14 04:43 UTC, svijaykumar-px commented on k8s/policyV1/poddisruptionbudgetV1.go
We cannot use the same policy.go file for both the versions as they use different client interfaces

2024-02-14 07:32 UTC, piyush-nimbalkar approved these changes

2024-02-14 07:32 UTC, piyush-nimbalkar commented on k8s/policy/poddisruptionbudget_v1beta1.go
> +// PodDisruptionBudgetOps is an interface to perform k8s Pod Disruption Budget operations
nit: V1Beta1Ops

2024-02-14 07:32 UTC, piyush-nimbalkar commented on k8s/policy/policy.go
> +	policyclient "k8s.io/client-go/kubernetes"
nit: We don't have to call it policyclient. It is a Kubernetes client with many APIs. So let's leave it as kubernetes.

2024-02-14 07:32 UTC, piyush-nimbalkar commented on k8s/policy/policy.go
> +	policy policyclient.Interface
nit: Let's rename the variable as just 'client' instead of policy now.

2024-02-14 08:14 UTC, merged